### ISSUE TITLE
Ensure MailChimp works after deployment

### ISSUE THREAD

**Issue by Tbyrne22** [Tbyrne22/deli_final_project#155]

**Comment by Tbyrne22** [comment]
1. Access Vercel Dashboard: Log in to your Vercel account and navigate to your project's dashboard.

2. Project Settings: Find your project and go to its settings.

3. Environment Variables: Look for a section or tab labeled "Environment Variables" or something similar.

4. Add Variables: Add each of your environment variables there:

**Comment by rhnjit** [comment]
Variables added. I didn't work immediately after. Looks like it took some time to take effect.
