### ISSUE TITLE
Perform competitive analysis for 3 competitors

### ISSUE THREAD

**Issue by rhnjit** [Tbyrne22/deli_final_project#20]
As a product manager I need to perform a competitive analysis for at least three competitors to better position the deli store above it's competitors in the local market.

**Acceptance criteria:**

1. Competitive analysis completed for 3 competitors
2. The archetype and methods of persuasion are identified for each competitor
3. Document linked to readme documentation

**Comment by Tbyrne22** [comment]
see Competitive Analysis document
